# Generated by Django 5.0.6 on 2024-05-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='landmark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
