# Generated by Django 5.0.6 on 2024-06-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_book_authors_cart_cartproduct_cart_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='cart_products',
        ),
    ]
